---
repository: "git-cherry-picker"
organization: "YouAppi"
gitUserName: "youBotty"
gitUserEmail: "botty@youappi.com"
gitUserPass: "3QEwW7yVk6YHuvLsBvktCTW_cnWSk626hcnsJblYCx8gLw00wQFlTggKztdSGyb4"
gmailUser: "botty@youappi.com"
gmailPass: "b-JMCMKSixMJETcwl0C75w"
