---
repository: "git-cherry-picker"
organization: "YouAppi"
gitUserName: "youBotti"
gitUserEmail: "botty@youappi.com"
gitUserPass: "3QEwW7yVk6YHuvLsBvktCTW_cnWSk626hcnsJblYCx8gLw00wQFlTggKztdSGyb4"
gmailUser: "ignore@youappi.com"
gmailPass: "pass"

approverTokens:
- "OTyzqlKv7lPD-WJfn4drKtxm_qb3MSnR4qWXkbee7P5cKKDb0ZPDdggKztdSGyb4"
