---
repository: "git-cherry-picker"
organization: "YouAppi"
gitUserName: "youBotti"
gitUserEmail: "botty@youappi.com"
gitUserPass: "3QEwW7yVk6YHuvLsBvktCTW_cnWSk626hcnsJblYCx8gLw00wQFlTggKztdSGyb4"
gmailUser: "ori.y@youappi.com"
gmailPass: "b-JMCMKSixMJETcwl0C75w"

approverTokens:
- "BZV3187ACQF7mlDDr70ikCsSs1hcY66tH-cgqKfQUA9r8wCMtelXEwgKztdSGyb4"
- "ykHrdveF7Nm00dZRjDfN69bh8Iwhuo-drtw9kAT1CC9WTwOx7nQQWggKztdSGyb4"
